// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeartBeat.proto

package chenbxxx.example.netty.netty_protocol_buffer;

public final class HeartBeatProto {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_HeartBeat_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_HeartBeat_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017HeartBeat.proto\"1\n\tHeartBeat\022\020\n\010heart_" +
                        "id\030\001 \001(\005\022\022\n\nheart_time\030\002 \001(\tB7\n%chenbxxx" +
                        ".actual.netty_protocol_bufferB\016HeartBeat" +
                        "Protob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_HeartBeat_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_HeartBeat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HeartBeat_descriptor,
                new java.lang.String[]{"HeartId", "HeartTime",});
    }

    private HeartBeatProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface HeartBeatOrBuilder extends
            // @@protoc_insertion_point(interface_extends:HeartBeat)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 heart_id = 1;</code>
         */
        int getHeartId();

        /**
         * <code>string heart_time = 2;</code>
         */
        java.lang.String getHeartTime();

        /**
         * <code>string heart_time = 2;</code>
         */
        com.google.protobuf.ByteString
        getHeartTimeBytes();
    }

    /**
     * Protobuf type {@code HeartBeat}
     */
    public static final class HeartBeat extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:HeartBeat)
            HeartBeatOrBuilder {
        public static final int HEART_ID_FIELD_NUMBER = 1;
        public static final int HEART_TIME_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:HeartBeat)
        private static final chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<HeartBeat>
                PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
            @java.lang.Override
            public HeartBeat parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HeartBeat(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat();
        }

        private int heartId_;
        private volatile java.lang.Object heartTime_;
        private byte memoizedIsInitialized = -1;

        // Use HeartBeat.newBuilder() to construct.
        private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private HeartBeat() {
            heartTime_ = "";
        }

        private HeartBeat(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            heartId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            heartTime_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.internal_static_HeartBeat_descriptor;
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<HeartBeat> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new HeartBeat();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.internal_static_HeartBeat_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat.class, chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat.Builder.class);
        }

        /**
         * <code>int32 heart_id = 1;</code>
         */
        public int getHeartId() {
            return heartId_;
        }

        /**
         * <code>string heart_time = 2;</code>
         */
        public java.lang.String getHeartTime() {
            java.lang.Object ref = heartTime_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                heartTime_ = s;
                return s;
            }
        }

        /**
         * <code>string heart_time = 2;</code>
         */
        public com.google.protobuf.ByteString
        getHeartTimeBytes() {
            java.lang.Object ref = heartTime_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                heartTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (heartId_ != 0) {
                output.writeInt32(1, heartId_);
            }
            if (!getHeartTimeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, heartTime_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (heartId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, heartId_);
            }
            if (!getHeartTimeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, heartTime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat)) {
                return super.equals(obj);
            }
            chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat other = (chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat) obj;

            if (getHeartId()
                    != other.getHeartId()) return false;
            if (!getHeartTime()
                    .equals(other.getHeartTime())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + HEART_ID_FIELD_NUMBER;
            hash = (53 * hash) + getHeartId();
            hash = (37 * hash) + HEART_TIME_FIELD_NUMBER;
            hash = (53 * hash) + getHeartTime().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HeartBeat> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code HeartBeat}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:HeartBeat)
                chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeatOrBuilder {
            private int heartId_;
            private java.lang.Object heartTime_ = "";

            // Construct using chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.internal_static_HeartBeat_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.internal_static_HeartBeat_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat.class, chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                heartId_ = 0;

                heartTime_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.internal_static_HeartBeat_descriptor;
            }

            @java.lang.Override
            public chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat getDefaultInstanceForType() {
                return chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat.getDefaultInstance();
            }

            @java.lang.Override
            public chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat build() {
                chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat buildPartial() {
                chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat result = new chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat(this);
                result.heartId_ = heartId_;
                result.heartTime_ = heartTime_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat) {
                    return mergeFrom((chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat other) {
                if (other == chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat.getDefaultInstance())
                    return this;
                if (other.getHeartId() != 0) {
                    setHeartId(other.getHeartId());
                }
                if (!other.getHeartTime().isEmpty()) {
                    heartTime_ = other.heartTime_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (chenbxxx.example.netty.netty_protocol_buffer.HeartBeatProto.HeartBeat) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 heart_id = 1;</code>
             */
            public int getHeartId() {
                return heartId_;
            }

            /**
             * <code>int32 heart_id = 1;</code>
             */
            public Builder setHeartId(int value) {

                heartId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 heart_id = 1;</code>
             */
            public Builder clearHeartId() {

                heartId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string heart_time = 2;</code>
             */
            public java.lang.String getHeartTime() {
                java.lang.Object ref = heartTime_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    heartTime_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string heart_time = 2;</code>
             */
            public Builder setHeartTime(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                heartTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string heart_time = 2;</code>
             */
            public com.google.protobuf.ByteString
            getHeartTimeBytes() {
                java.lang.Object ref = heartTime_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    heartTime_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string heart_time = 2;</code>
             */
            public Builder setHeartTimeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                heartTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string heart_time = 2;</code>
             */
            public Builder clearHeartTime() {

                heartTime_ = getDefaultInstance().getHeartTime();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:HeartBeat)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
